version: '3.6'

services:
  mysql:
    image: mysql:8.0.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newsletter
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    ports:
      - 5432:5432
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:3.0
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 5000:80